# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7060ae65e874c5e83fffab92a110ce8a89715e0580279d273c6605beadbc69f75e6c26e0377af3e8ca7be36b99db7031823c5aadafc6bb0695c55b970c69253

test:
  secret_key_base: e089c8c32f5bb473a3306589c2b93e42a73677dd2c10f9a807b15ba4a315aff26dedce20575a1c4c88c45d3897ca1af3b0271368d58be827ff23ebfa64a3c3fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
